# Generated by Django 2.2.3 on 2020-04-10 22:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dating_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='instantmessage',
            old_name='created',
            new_name='date',
        ),
    ]
