# Generated by Django 2.2.3 on 2020-04-11 20:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dating_app', '0002_auto_20200410_2231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instantmessage',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='senderr', to=settings.AUTH_USER_MODEL),
        ),
    ]
