# Generated by Django 2.2.3 on 2020-04-13 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dating_app', '0004_auto_20200413_1930'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='conversation',
            options={'ordering': ['-instantmessage__date']},
        ),
    ]
