# Generated by Django 2.2.3 on 2020-04-13 22:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dating_app', '0005_auto_20200413_1946'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='conversation',
            options={},
        ),
    ]
