# Generated by Django 2.2.3 on 2020-04-22 19:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dating_app', '0006_auto_20200413_2222'),
    ]

    operations = [
        migrations.RenameField(
            model_name='instantmessage',
            old_name='receiver',
            new_name='conversation',
        ),
        migrations.AlterField(
            model_name='instantmessage',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender', to=settings.AUTH_USER_MODEL),
        ),
    ]
