# Generated by Django 2.2.3 on 2020-04-25 00:39

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('dating_app', '0007_auto_20200422_1947'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instantmessage',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 25, 0, 39, 10, 727867, tzinfo=utc), verbose_name='Date de création'),
        ),
    ]
