# Generated by Django 2.2.3 on 2020-04-27 18:46

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('dating_app', '0012_auto_20200426_2007'),
    ]

    operations = [
        migrations.AddField(
            model_name='instantmessage',
            name='viewed',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='instantmessage',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 27, 18, 46, 42, 809587, tzinfo=utc), verbose_name='Data creation'),
        ),
    ]
