# Generated by Django 2.2.3 on 2020-05-03 19:47

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('dating_app', '0013_auto_20200427_1846'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instantmessage',
            name='conversation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversation', to='dating_app.Conversation'),
        ),
        migrations.AlterField(
            model_name='instantmessage',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 3, 19, 47, 28, 445248, tzinfo=utc), verbose_name='Data creation'),
        ),
    ]
