# Generated by Django 2.2.3 on 2020-05-03 20:11

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('dating_app', '0014_auto_20200503_1947'),
    ]

    operations = [
        migrations.AddField(
            model_name='instantmessage',
            name='receiver',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='receiver', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='instantmessage',
            name='conversation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dating_app.Conversation'),
        ),
        migrations.AlterField(
            model_name='instantmessage',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 3, 20, 11, 1, 263179, tzinfo=utc), verbose_name='Data creation'),
        ),
    ]
